# [Обязательное] Название сайта
site_name: ВСК OpenAPI

# Базовый адрес сайта
site_url: https://www.mkdocs.org/

# Описание сайта. Добавляется в meta в html-заголовке каждой страницы.
site_description: Project documentation with Markdown.

# Автор (или авторы) сайта. Добавляется в html-заголовок каждой страницы.
site_author: MkDocs Team

# Ссылка на репозиторий, в котором хранятся исходные материалы.
repo_url: https://github.com/mkdocs/mkdocs/

# Относительный путь, который в сочетании со ссылкой на репозиторий (repo_url)
# и относительным адресом страницы даст адрес, по которому можно вызвать
# редактор страницы. Для repo_url-ов известных площадок (например,
# GitHub или GitLab можно оставить пустым - он подставится автоматически)
edit_uri: ""

# Информация о теме, которая будет применена для сгенерированного сайта.
# И её параметрах
theme:
    name: material    
#    locale: en
#    analytics: {gtag: 'G-274394082'}
#    highlightjs: true
#    hljs_languages:
#        - yaml
#        - django

# Структура навигации генерируемого сайта.
nav:
    - Home: index1.md
    - Авторизация: auth.md
    - Getting Started: getting-started.md
    - Продукты:
        - Policy: products/policy.md
        - Cargo: products/cargo.md
    - Методы:
        - Overview: api/index.md
        

#extra_css:
#    - css/extra.css

# Список подключённых расширений для препроцессора языка Markdown
#markdown_extensions:
#    - toc:
#        permalink: 
#    - admonition
#    - attr_list
#    - def_list
#    - mdx_gh_links:
#        user: mkdocs
#        repo: mkdocs

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>.

# Список использованных плагинов MkDocs
#plugins:
#    - search
#    - redirects:
#        redirect_maps:
#            user-guide/plugins.md: dev-guide/plugins.md
#            user-guide/custom-themes.md: dev-guide/themes.md
#            user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md

theme: jekyll-theme-cayman